/**
 * Famous plane-spotting locations — beaches under the threshold, factory
 * strips, boneyards, terrifying approaches. [name, lat, lon, tags[], blurb].
 * Hand-curated public-knowledge coordinates; blurbs are original text.
 */
export const HOTSPOTS = [
  ['Maho Beach', 18.0398, -63.1179,
    ['sxm', 'beach', 'heavies'],
    'Jets blast the beach at Princess Juliana — the classic.'],
  ['LAX In-N-Out', 33.9455, -118.403,
    ['burgers', 'heavies'],
    'A double-double under the 24R approach.'],
  ['Heathrow Myrtle Avenue', 51.4646, -0.4194,
    ['heavies', 'approach'],
    'Heavies every 90 seconds over the garden fence on 27L final.'],
  ['Gravelly Point', 38.863, -77.0454,
    ['dca', 'river-visual'],
    'Planes 100ft overhead flying the Potomac river visual into DCA.'],
  ['Anchorage Cargo Ramp', 61.1769, -149.986,
    ['cargo', '747'],
    "The world's 747-freighter capital — the Asia–US techstop."],
  ['Gander', 48.9369, -54.568,
    ['ferry', 'history'],
    'The transatlantic crossroads — ferry flights and diversions since 1938.'],
  ['Keflavík', 63.985, -22.6056,
    ['ferry', 'arctic'],
    'North Atlantic ferry stop — everything crossing pauses here.'],
  ['Frankfurt Spotting Hill', 50.033, 8.526,
    ['heavies'],
    'The famous dune at the west end of the field.'],
  ['Amsterdam Polderbaan', 52.3286, 4.7086,
    ['close-up'],
    'Bikes, benches and jets at eye level beside the Polderbaan.'],
  ['Haneda Rooftop Decks', 35.5494, 139.7798,
    ['city-view'],
    'Observation decks with Mount Fuji behind the traffic.'],
  ['Botany Bay Approach', -33.964, 151.183,
    ['beach', 'sydney'],
    'Sydney 34L arrivals skim the Botany Bay kitesurfers.'],
  ['Oshkosh', 43.9844, -88.557,
    ['airventure', 'ga'],
    'AirVenture: the busiest airspace on Earth for one week each July.'],
  ['Mojave Air & Space Port', 35.0594, -118.1517,
    ['storage', 'test', 'space'],
    'Stored airliners next to experimental spaceplanes.'],
  ['Victorville', 34.5975, -117.383,
    ['storage', 'boneyard'],
    'Desert widebody storage — rows of retired 747s.'],
  ['Pinal Airpark', 32.5106, -111.3275,
    ['storage', 'boneyard'],
    'A quiet desert boneyard — ex-airline heavies sunbathing.'],
  ['Paine Field', 47.9063, -122.2816,
    ['boeing', 'factory'],
    'The Boeing widebody line + Future of Flight observation deck.'],
  ['Toulouse-Blagnac', 43.6293, 1.3638,
    ['airbus', 'factory'],
    'A350s and Beluga XLs fresh off the Airbus line.'],
  ['Hamburg Finkenwerder', 53.5353, 9.8357,
    ['airbus', 'factory'],
    "Airbus's riverside factory strip — Belugas daily."],
  ['Boeing Charleston', 32.899, -80.0405,
    ['boeing', 'factory', '787'],
    '787 Dreamliners hatch here.'],
  ['St. Barthélemy', 17.9044, -62.8442,
    ['scary-approach'],
    "The hillside plunge onto one of aviation's shortest strips."],
  ['Saba', 17.645, -63.22,
    ['shortest-runway'],
    'The shortest commercial runway on Earth — 400 meters of cliff edge.'],
  ['Skiathos', 39.1771, 23.5037,
    ['beach', 'greek-maho'],
    'The Greek Maho — jets inches over the harbor road.'],
  ['Innsbruck Approach', 47.2602, 11.344,
    ['alps', 'scary-approach'],
    'Jets threading the Alps — special crew certification required.'],
  ['Courchevel', 45.3967, 6.6347,
    ['altiport', 'scary-approach'],
    'The 18.6% uphill altiport from the Bond film.'],
  ['Madeira', 32.6979, -16.7745,
    ['scary-approach', 'atlantic'],
    'The runway on stilts jutting into the Atlantic.'],
  ['Gibraltar', 36.1511, -5.3497,
    ['runway-road'],
    'A highway crosses the runway; the Rock towers over final.'],
  ['Lukla', 27.6869, 86.7314,
    ['everest', 'scary-approach'],
    'The Everest gateway: 527 uphill meters at 9,300ft.'],
  ['Paro', 27.4032, 89.4246,
    ['himalaya', 'scary-approach'],
    'Only a handful of pilots are certified for this Himalayan slalom.'],
  ['Toncontín', 14.0608, -87.2172,
    ['scary-approach'],
    'The infamous last-second checkerboard turn onto runway 02.'],
  ['Queenstown Approach', -45.021, 168.739,
    ['alps', 'nz'],
    'Airliners banking through the Remarkables.'],
];
